- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  startingGear: PrisonerGear
  alwaysUseSpawner: true
  canBeAntag: false
  whitelistRequired: true
  icon: "Prisoner"
  supervisors: job-supervisors-security
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600
  special:
  - !type:AddComponentSpecial
    components:
    - type: PrisonerAccent


- type: startingGear
  id: PrisonerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
    id: PrisonerPDA
    ears: ClothingHeadsetGrey
  innerclothingskirt: ClothingUniformJumpsuitPrisoner
